### ISSUE TITLE
Sort payloads into categories

### ISSUE THREAD

**Issue by sundhaug92** [hak5/packetsquirrel-payloads#2]
As put down by the documentation at https://www.hak5.org/gear/packet-squirrel/docs, under the section "Payload Development", sub-section "Payload Best Practices / Style Guide". Categorization for existing payloads proposed in #1.

**Comment by thehappydinoa** [comment]
For everyone who would like to contribute to this please check [this forum thread](https://forums.hak5.org/topic/42103-categorization/).

**Comment by sebkinne** [comment]
I'm down with this. PR welcome.
