### ISSUE TITLE
Dead link in recovery console

### ISSUE THREAD

**Issue by DidierStevens** [hak5/packetsquirrel-payloads#24]
I did test the recovery console (http://192.168.1.1), it worked, but the link to the recovery firmware on the recovery console is dead: https://downloads.packetsquirrel.com/

![image](https://user-images.githubusercontent.com/6815601/32750665-ae44bd5c-c8c3-11e7-96a3-759acd3d7c2b.png)

**Comment by sebkinne** [comment]
Thanks for reporting this - I have fixed the DNS issue.
