### ISSUE TITLE
Default payloads do not appear to match description in documentation

### ISSUE THREAD

**Issue by sundhaug92** [hak5/packetsquirrel-payloads#3]
On github, the defaults are all dummy-payloads, however the docs at https://www.hak5.org/gear/packet-squirrel/docs describe the following setup:

|Switch |Payload    |
|--------|-----------|
|switch1|TCPdump |
|switch2|DNSSpoof|

**Comment by sundhaug92** [comment]
Looked it up. The recovery-image at https://packetsquirrel.com/squirrel-recovery.bin matches the description in the documentation but does not match the github.

**Comment by sebkinne** [comment]
This is done on purpose. You are supposed to populate switch1 and switch2 payloads yourself.

We made the built in payloads available, because you might want to run multiple variations of one.
